name = "XYZ"
uuid = "2b4abb15-f868-42b1-8652-209b8e29064d"
authors = ["Christian Guetnga <lsdrfrx@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
